### ISSUE TITLE
Unable to execute DOS .com file directly in blink16

### ISSUE THREAD

**Issue by alexjeffburke** [ghaerr/blink16#2]
Hi there,
I assembled a .com file using nasm but seem to be unable to run it. Attempts to do so result in a "command not found" error from the blink16 executable. The invocation I'm using from within the blink16 folder within a repo checkout is as follows:

```sh
./blink16 hello.com
./blink16: command not found: hello.com
```

Unsure if I'm doing something wrong or have left out a required option or such, but as suggested on discord I've attached a simple .com that writes "Hello world!" to stdout and exits via int 21h calls verified working under MS-DOS 3.3 in 86box.

Thanks!
[hello.com.zip](https://github.com/ghaerr/blink16/files/10968933/hello.com.zip)

**Comment by ghaerr** [comment]
Hello @alexjeffburke,

Thanks for posting this. It should be fixed now in 18bff1cc6a83e4a43d9f1f6e93e63481b0824575.

Thank you!

**Comment by alexjeffburke** [comment]
@ghaerr apologies not to respond sooner - appreciate your for taking a look and patching the issue. Tested it on a larger nasm generated COM file and it worked (though iirc I then hit an instruction issue that I’ll try to open separately next I attempt it). Thanks :)

**Comment by ghaerr** [comment]
No problem, thanks for the response. Currently, blink16 exits on any invalid instruction, which I've been meaning to fix. I've also been running into a few instructions that aren't implemented, but all 8086 instructions are, so perhaps 80186 instructions need to be added. If you need 32-bit instructions, we'll need to use the original blink, but it doesn't support DOS  .com files (yet).

When blink16 exits on an invalid instruction, the IP pointer is usually already incremented by 1. In order to better see the problem, you can use `blink16 -b CS:IP foo.com` with CS:IP set to the value shown at exit (subtracting one from IP).

**Comment by ghaerr** [comment]
Blink16 now no longer exits on an invalid instruction; instead an error is displayed and the display is still active, allowing for better debugging.
