### ISSUE TITLE
Blink16 inside Elks

### ISSUE THREAD

**Issue by toncho11** [ghaerr/blink16#6]
I think it was a difficult project, but would it be possible to port blink16 to run inside Elks. This can allow some Dos binaries to run. I mean now that we have the open watcom compiler and the fact that we can access more memory.

**Comment by ghaerr** [comment]
No, there's no chance blink16 can run on actual 8086 hardware, as the program statically allocates a 1M byte array for the emulated memory - far more than will fit on any such system!

**Comment by toncho11** [comment]
It can not be reduced to 300 kb for example? Even if allows small programs to be emulated, it will still be interesting. 
Some kind of mapping into these 300kb and the moment more is requested then it will crash. I mean a blink16 port with limitations.

**Comment by toncho11** [comment]
With DOOM we were able to use more than 500 kb.

**Comment by ghaerr** [comment]
The emulated memory could be reduced with great effort, but the BIOS runs at the very top of 1M and the interrupt vectors are at the very bottom, so not sure how anything would work. 

Blink16 is mostly an 8086 instruction set emulator, not a full-system (meaning peripherals like EGA, etc) emulator. That means that, even when emulating user mode DOS programs, (as opposed to emulating a hardware system), very many DOS games write directly to the hardware, which is not supported by blink16. The reasons for this are many, but in general the only reliable way of emulating real hardware (quickly) is to run in a virtual machine (VM) mode, which requires a 32-bit CPU (and a different approach than blink16 takes). Running blink16 on an 8086 would cause programs to likely run 10-100x slower than normal, even at full speed.

If you're really trying to run DOS programs on ELKS on real 8086 hardware, (and don't want to reboot which is by far the best approach), writing a bunch of code to emulate the INT 21 system call interface and just letting the programs run on the real CPU and real hardware would be a better approach, IMO. However, since many more complicated DOS programs reprogram the hardware PIT and such, the system might have to be rebooted after running them after all anyways.
